### ISSUE TITLE
Applikation gegen HTML/Skript Injektion schützen

### ISSUE THREAD

**Issue by marci9494** [marci9494/carSharing#11]
Auch Cross-Site-Skripting genannt

**Comment by marci9494** [comment]
Bitte alles ${feldName} felder die wir ausgeben zu folgendem ändern:
<c:out value="${feldName}" />

Wichtig ist, das ganz oben in der JSP folgendes importiert wird
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %> <-- haben wir bereits fast überall

**Comment by marci9494** [comment]
Ebenso folgendes: 
  99         protected static String xss(String value) {
 100                 String newValue = null;
 101                 if (value != null) {
 102                         PolicyFactory policy = new HtmlPolicyBuilder().toFactory();
 103                         newValue = policy.sanitize(value);
 104                 }
 105                 return newValue;
 106         }

**Comment by cetine** [comment]
Das Zweite versteh ich nicht?

**Comment by cetine** [comment]
"<c:out value=..." hab ich versucht aber schmeißt folgenden fehler raus:
**org.apache.jasper.JasperException: /WEB-INF/views/cars_detail.jsp (line: [25], column: [18]) quote symbol expected**

**Comment by marci9494** [comment]
done
