### ISSUE TITLE
Kilometerpreis bei Fahrzeug entfernen

### ISSUE THREAD

**Issue by marci9494** [marci9494/carSharing#23]

**Comment by jonasellinger** [comment]
Wirklich nun entfernen? Wie werden dann nun die Buchungskosten berechnet? Nur auf Tagesbasis?

**Comment by marci9494** [comment]
Stand jetzt, nur auf Tagesbasis

**Comment by jonasellinger** [comment]
Aus Zeitgründen Entfernung durchaus sinnvoll.
Änderungen published
- Löschung aus allen Projektstellen
- Löschung der Spalte aus Tabelle Fahrzeug (update24)
