### ISSUE TITLE
Startseite: Begrüßung

### ISSUE THREAD

**Issue by Janphilipphils** [marci9494/carSharing#25]
Startseite "Herzlich Willkommen" befindet sich rechts ohne Formatierung oder ähnliches
Hoffentlich so nicht gewollt.

**Comment by jonasellinger** [comment]
Problem konnte ich leider nicht nachvollziehen. 

un-eingeloggt:
![image](https://user-images.githubusercontent.com/12181977/37294411-0673bd52-2616-11e8-93ab-6bebe4b2bee4.png)

eingeloggt:
![image](https://user-images.githubusercontent.com/12181977/37294459-1ad78e36-2616-11e8-8bd4-29c6c02993f0.png)

Wo ist das Problem? :P
