### ISSUE TITLE
registrieren -Passwort-

### ISSUE THREAD

**Issue by Janphilipphils** [marci9494/carSharing#26]
registrieren möglich, obwohl Passwörter nicht übereinstimmen

**Comment by marci9494** [comment]
@jonasellinger ich glaube das hattest du mal implementiert?

**Comment by jonasellinger** [comment]
Mit Chrome und Firefox getestet.
Funktioniert nun (wieder). Beide Eingaben müssen wieder übereinstimmen, sonst Popup.
