### ISSUE TITLE
Aktuell kann man nur BMW vermieten

### ISSUE THREAD

**Issue by cetine** [marci9494/carSharing#32]
Egal was für Marken bei der Fahrzeugregistrierung gewählt werden es steht bei /cars/ und /cars_detail immer BMW dran!

**Comment by marci9494** [comment]
liegt an folgendem:
		FahrzeugHersteller foundHersteller = herstellerService.getHerstellerById("1");
		FahrzeugKategorie foundKategorie = kategorieService.getFahrzeugKategorieById("1");

D.h. Hersteller,Farbe,Kategorie müssen aus der Datenbank ausgelesen werden und angezeigt werden. Anschließend können die richtige werte abgespeichert werden

**Comment by jonasellinger** [comment]
Es wird nun der wirklich ausgewählte Hersteller hochgeladen (lokal).

Für Kategorie wird weiterhin 1 hochgeladen. Aktuell sind ohnehin keine anderen Kategorien vorhanden. Für Projektabschluss auch nicht unbedingt notwendig.
