### ISSUE TITLE
cars: Zwei Buttons, selbe Funktion

### ISSUE THREAD

**Issue by jonasellinger** [marci9494/carSharing#34]
Unter cars gibt es pro Fahrzeug zwei Buttons.
Beide Buttons führen aber zur selben Seite (cars_details). 
Sollte auf einen Button reduziert werden?

![image](https://user-images.githubusercontent.com/12181977/37337280-10282f88-26b4-11e8-9f6c-c24d0cdc4f0a.png)

**Comment by CorinnaHauser** [comment]
Sollte ja so sein, bei Vermieten wirst du ja auf den unteren Teil der Seite verwiesen :)
