### ISSUE TITLE
Problem bei Profil bearbeiten

### ISSUE THREAD

**Issue by CorinnaHauser** [marci9494/carSharing#36]
- Anrede lässt sich nicht verändern
- Kreditkarteninfo wird falsch dargestellt (siehe Bild)

![image](https://user-images.githubusercontent.com/35527711/37340148-6cc38dd8-26bd-11e8-8ae3-8f004004d01a.png)

**Comment by jonasellinger** [comment]
- Anrede soll nicht veränderbar sein
- Konnte Problem mit Darstellung der KK nicht reproduzieren (Firefox & Chrome)
![image](https://user-images.githubusercontent.com/12181977/37344008-69480dc6-26c9-11e8-9fce-87f4e1493979.png)
