### ISSUE TITLE
Darstellungsfehler auf allen Seiten

### ISSUE THREAD

**Issue by jonasellinger** [marci9494/carSharing#40]
Auf allen Seiten gibt es ein Darstellungsproblem

![image](https://user-images.githubusercontent.com/12181977/37511812-7783e0ac-2900-11e8-8f5c-03e06244335e.png)

![image](https://user-images.githubusercontent.com/12181977/37511828-8474bb56-2900-11e8-9d04-39c579a3f9a8.png)

**Comment by marci9494** [comment]
Done - Navigation wurde allerdings nicht angefasst.
